name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      TERM: linux

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make
      
 
